ci: fix coverage badge and drop coverage comments on PRs (#203)
* ci: move coverage badge to separate workflow

* ci: drop pytest-coverage-comment due to errors

Currently, running pytest-coverage-comment will cause permission errors
when a PR is opened from a fork even with full workflow permissions:

No previous comment found, creating a new one
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration

See
https://github.com/MishaKav/pytest-coverage-comment/issues/68